# Generated by Django 4.1.1 on 2022-10-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='parking_meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parkingmeter'),
        ),
    ]
